macos_option_as_alt left
allow_remote_control yes
listen_on unix:/tmp/mykitty
enabled_layouts splits

# Spotify sidebar (right, 15% width)
map ctrl+shift+s launch --location=vsplit --bias=15 spotify_player



# BEGIN_KITTY_THEME
# Eldritch
include current-theme.conf
# END_KITTY_THEME